config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :mytweets do
    post :confirm, on: :collection
    patch :confirm, on: :member
    # get :top, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mytweet.rb
class Mytweet < ApplicationRecord
  validates :content, presence: true
  validates :content, length:{in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mytweets_controller.rb
class MytweetsController < ApplicationController
  before_action :set_mytweet, only: [:shoe, :edit, :update, :destroy]
  def index
    @mytweets = Mytweet.all
  end
  def new
    @mytweet = Mytweet.new
  end
  def create
    @mytweet = Mytweet.new(mytweet_params)
    if params[:back]
      render :new
    else
      if @mytweet.save
        redirect_to mytweets_path, notice:"tweetしました"
      else
        render :new
      end
    end
  end
  def show
    @mytweet =Mytweet.find(params[:id])
  end
  def edit
    @mytweet = Mytweet.find(params[:id])
  end
  def update
    @mytweet = Mytweet.find(params[:id])
    if params[:back]
      render  :edit
    else
      if @mytweet.update(mytweet_params)
        redirect_to mytweets_path, notice:"編集しました"
      else
        render :edit
      end
    end
  end
  def confirm
    @mytweet = Mytweet.new(mytweet_params)
    @mytweet.id = params[:id]
    render :new if @mytweet.invalid?
  end
  def destroy
    @mytweet.destroy
    redirect_to mytweets_path, notice:"tweetを削除しました"
  end

  private
  def mytweet_params
    params.require(:mytweet).permit(:id, :content)
  end
  def set_mytweet
    @mytweet = Mytweet.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mytweets_helper.rb
module MytweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_mytweets_path
    elsif action_name == 'edit'
      confirm_mytweet_path
    end
  end

  def confirm_new_or_edit
    unless @mytweet.id?
      mytweets_path
    else
      mytweet_path
    end
  end

  def confirm_form_method
    @mytweet.id ? 'patch' : 'post'
  end

end

app/helpers/top_helper.rb
module TopHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
  <p>運営yasuko</p>
</footer>

app/views/application/_header.html.erb
<header class="header clearfix">
  <nav>
   <ul class="top_menu clearfix">
      <li><%= link_to "TOP",root_path %></li>
      <li><%= link_to "INDEX",mytweets_path %></li>
      <li><%= link_to "TWEET",new_mytweet_path %></li>
    </ul>
  </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YasukoTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mytweets/_form.html.erb
<div class="content">
<%= form_with(model: @mytweet, local:true, url: choose_new_or_edit ) do |form| %>
  <% if @mytweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @mytweet.errors.count %>件のエラーがあります！</h2>
      <ul>
      <% @mytweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mytweet_content">
    <%= form.label :tweet %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "indexにもどる",mytweets_path %>
</div>

app/views/mytweets/_header.html.erb
<header class="header clearfix">
  <nav>
   <ul class="top_menu clearfix">
      <li><%= link_to "TOP",mytweets_top_path %></li>
      <li><%= link_to "INDEX",mytweets_path %></li>
      <li><%= link_to "TWEET",new_mytweet_path %></li>
    </ul>
  </nav>
  </header>

app/views/mytweets/confirm.html.erb
<%= render 'header' %>
<div class="content_confirm">
<h3 class="text-left">以下の内容でつぶやく</h3>
<%= form_with(model: @mytweet, url: confirm_new_or_edit, method: confirm_form_method, local:true) do |form| %>
  <%= form.hidden_field :content %>
  <p>内容：<%= @mytweet.content %></p>
  <%= form.submit "つぶやく" %>
  <%= form.submit "もどる" ,name: 'back' %>
<% end %>
<%= link_to "indexにもどる",mytweets_path %>
</div>
<%= render 'footer' %>

app/views/mytweets/edit.html.erb
<%= render 'header' %>
<div class="content_edit">
<h2 class="text-left">編集する</h2>
<%= render 'form' %>
</div>
<%= render 'footer' %>

app/views/mytweets/index.html.erb
<%= render 'header' %>
<div class="container">
<div class="content">
<h1 class="text-left">mytweets一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>内容</th>
  </tr>
<% @mytweets.each do |mytweet| %>
  <tr>
    <td><%= mytweet.content %></td>
    <td><%= link_to '編集',edit_mytweet_path(mytweet.id),class:"btn btn-outline-info"%></td>
    <td><%= link_to '削除',mytweet_path(mytweet.id),method: :delete, data:{ confirm:'本当に削除しますか？'}, class:"btn btn-outline-danger"%></td>
  </tr>
<% end %>
</table>
<%= link_to 'つぶやく', new_mytweet_path, class:"btn btn-warning"%>
</div>
</div>
<%= render 'footer' %>

app/views/mytweets/new.html.erb
<%= render 'header' %>
<div class="content_new">
<h2 class="text-left">つぶやく</h2>
<%= render 'form' %>
</div>
<%= render 'footer' %>

app/views/mytweets/show.html.erb
<%= render 'header' %>
<div class="content_show">
<h1 class="text-left">mytweet詳細画面</h1>
<p>つぶやき：<%= @mytweet.content %></p>
<%= link_to 'indexにもどる', mytweet_path %>
</div>
<%= render 'footer' %>

app/views/mytweets/top.html.erb
<%= render 'header' %>
<h1>TOP</h1>
<%= image_tag 'image.png', :width => '400',class:"min-vw-100" %>
<%= render 'footer' %>

app/views/top/index.html.erb
<%= render 'header' %>
<h1>TOP</h1>
<%= image_tag 'image.png', :width => '400',class:"min-vw-100" %>
<%= render 'footer' %>